// src/utils/complaintData.js

export const sampleComplaints = [
  {
    title: "Garbage not collected",
    description: "Waste bins overflowing for three days near MG Road.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.6102, 12.9716],
      address: "MG Road, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-17T11:00:00.000Z",
  },
  {
    title: "Streetlight not working",
    description: "Streetlight near Brigade Road is not functioning.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.6086, 12.9756],
      address: "Brigade Road, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-16T20:00:00.000Z",
  },
  {
    title: "Pothole near Silk Board",
    description: "Huge pothole causing traffic near Silk Board junction.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.6245, 12.9177],
      address: "Silk Board, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-15T09:00:00.000Z",
  },
  {
    title: "Low water pressure",
    description: "Water supply is irregular in Koramangala 6th Block.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.6271, 12.9352],
      address: "Koramangala 6th Block, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-15T08:30:00.000Z",
  },
  {
    title: "Garbage dumped illegally",
    description: "Unauthorized garbage dumping near Whitefield Main Road.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.7500, 12.9719],
      address: "Whitefield Main Road, Bengaluru, Karnataka",
    },
    status: "Resolved",
    createdAt: "2025-09-14T18:00:00.000Z",
  },
  {
    title: "Broken streetlight",
    description: "Streetlight near Indiranagar 100ft Road is broken.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.6408, 12.9784],
      address: "100ft Road, Indiranagar, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-14T10:00:00.000Z",
  },
  {
    title: "Overflowing drainage",
    description: "Drainage overflow near Majestic bus stand.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.5726, 12.9763],
      address: "Majestic, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-13T19:00:00.000Z",
  },
  {
    title: "Water leakage",
    description: "Pipe leakage observed near Jayanagar 4th Block market.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.5930, 12.9250],
      address: "Jayanagar 4th Block, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-13T12:00:00.000Z",
  },
  {
    title: "Garbage unattended",
    description: "Garbage piled up for a week in Rajajinagar.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.5552, 12.9981],
      address: "Rajajinagar, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-12T15:00:00.000Z",
  },
  {
    title: "Flickering streetlight",
    description: "Streetlight flickers constantly in Malleshwaram.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.5680, 13.0027],
      address: "Malleshwaram, Bengaluru, Karnataka",
    },
    status: "Resolved",
    createdAt: "2025-09-12T09:00:00.000Z",
  },
  {
    title: "Road filled with potholes",
    description: "Potholes all along Outer Ring Road near Marathahalli.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.6974, 12.9569],
      address: "Outer Ring Road, Marathahalli, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-11T17:30:00.000Z",
  },
  {
    title: "Irregular water supply",
    description: "Residents of Banashankari are facing irregular water supply.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.5586, 12.9257],
      address: "Banashankari, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-11T14:00:00.000Z",
  },
  {
    title: "Unattended garbage",
    description: "Waste not cleared for 5 days near Hebbal flyover.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.5970, 13.0352],
      address: "Hebbal, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-11T09:00:00.000Z",
  },
  {
    title: "Broken lamp post",
    description: "Lamp post bent near Electronic City Phase 1.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.6670, 12.8390],
      address: "Electronic City Phase 1, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-10T20:00:00.000Z",
  },
  {
    title: "Manhole left open",
    description: "Dangerous open manhole near KR Market.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.5800, 12.9613],
      address: "KR Market, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-10T15:00:00.000Z",
  },
  {
    title: "Dirty drinking water",
    description: "Brown colored water supplied in RT Nagar.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.6006, 13.0231],
      address: "RT Nagar, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-10T09:30:00.000Z",
  },
  {
    title: "Garbage burning",
    description: "Locals burning garbage near Yeshwanthpur railway station.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.5546, 13.0184],
      address: "Yeshwanthpur, Bengaluru, Karnataka",
    },
    status: "Resolved",
    createdAt: "2025-09-09T19:30:00.000Z",
  },
  {
    title: "Streetlight timer issue",
    description: "Streetlights at HSR Layout switch off too early.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.6412, 12.9104],
      address: "HSR Layout, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-09T10:00:00.000Z",
  },
  {
    title: "Damaged footpath",
    description: "Broken pavement slabs in Ulsoor.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.6280, 12.9830],
      address: "Ulsoor, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-09T08:00:00.000Z",
  },
  {
    title: "Water contamination",
    description: "Residents of Bellandur report foul-smelling water.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.6784, 12.9279],
      address: "Bellandur, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-08T20:30:00.000Z",
  },
  {
    title: "Uncollected garbage",
    description: "Garbage not picked up in Basavanagudi.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.5737, 12.9402],
      address: "Basavanagudi, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-08T17:00:00.000Z",
  },
  {
    title: "Defunct streetlight",
    description: "Streetlight not working near Lalbagh.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.5883, 12.9507],
      address: "Lalbagh, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-08T09:00:00.000Z",
  },
  {
    title: "Huge potholes",
    description: "Multiple potholes on Mysuru Road stretch.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.5413, 12.9551],
      address: "Mysuru Road, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-07T19:30:00.000Z",
  },
  {
    title: "Irregular supply",
    description: "Water supply irregular in Vijayanagar.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.5301, 12.9711],
      address: "Vijayanagar, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-07T10:00:00.000Z",
  },
  {
    title: "Overflowing bins",
    description: "Garbage bins overflowing in Kengeri.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [77.4820, 12.9075],
      address: "Kengeri, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-07T09:30:00.000Z",
  },
  {
    title: "Damaged pole",
    description: "Electric pole damaged near Yelahanka.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [77.5963, 13.1007],
      address: "Yelahanka, Bengaluru, Karnataka",
    },
    status: "Resolved",
    createdAt: "2025-09-06T21:00:00.000Z",
  },
  {
    title: "Open drainage",
    description: "Open sewage drains near Peenya Industrial Area.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [77.4991, 13.0342],
      address: "Peenya, Bengaluru, Karnataka",
    },
    status: "Pending",
    createdAt: "2025-09-06T18:00:00.000Z",
  },
  {
    title: "No water supply",
    description: "Residents in BTM Layout face zero water supply today.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [77.6100, 12.9166],
      address: "BTM Layout, Bengaluru, Karnataka",
    },
    status: "In Progress",
    createdAt: "2025-09-06T10:00:00.000Z",
  },
  {
    title: "Garbage not collected",
    description: "Waste bins overflowing for three days near Main Road.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.3096, 23.3441],
      address: "Main Road, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-17T11:00:00.000Z",
  },
  {
    title: "Streetlight not working",
    description: "Streetlight near Lalpur Chowk is not functioning.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3430, 23.3585],
      address: "Lalpur Chowk, Ranchi, Jharkhand",
    },
    status: "In Progress",
    createdAt: "2025-09-16T20:00:00.000Z",
  },
  {
    title: "Potholes on road",
    description: "Large potholes near Kanke Road making traffic difficult.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.3200, 23.4000],
      address: "Kanke Road, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-16T15:00:00.000Z",
  },
  {
    title: "Low water pressure",
    description: "Water supply is irregular in Harmu Housing Colony.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.3033, 23.3471],
      address: "Harmu Colony, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-16T09:00:00.000Z",
  },
  {
    title: "Illegal dumping of garbage",
    description: "Garbage being dumped in open near Ratu Road.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.2870, 23.3670],
      address: "Ratu Road, Ranchi, Jharkhand",
    },
    status: "Resolved",
    createdAt: "2025-09-15T18:00:00.000Z",
  },
  {
    title: "Flickering streetlight",
    description: "Streetlight flickers constantly in Bariatu area.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3655, 23.3812],
      address: "Bariatu, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-15T11:00:00.000Z",
  },
  {
    title: "Drainage clogged",
    description: "Overflowing drainage near Doranda College.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.3202, 23.3155],
      address: "Doranda, Ranchi, Jharkhand",
    },
    status: "In Progress",
    createdAt: "2025-09-14T20:00:00.000Z",
  },
  {
    title: "Water leakage",
    description: "Water pipe leaking near Dangratoli Chowk.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.3335, 23.3433],
      address: "Dangratoli Chowk, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-14T17:30:00.000Z",
  },
  {
    title: "Garbage unattended",
    description: "Garbage piled up for a week in Kokar.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.3605, 23.3911],
      address: "Kokar, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-14T12:00:00.000Z",
  },
  {
    title: "Broken streetlight",
    description: "Streetlight broken near Hatia railway station.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3240, 23.3080],
      address: "Hatia, Ranchi, Jharkhand",
    },
    status: "Resolved",
    createdAt: "2025-09-14T10:00:00.000Z",
  },
  {
    title: "Manhole uncovered",
    description: "Open manhole near Birsa Chowk is a danger to pedestrians.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.3140, 23.3200],
      address: "Birsa Chowk, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-13T20:00:00.000Z",
  },
  {
    title: "Irregular water supply",
    description: "Residents of Morabadi facing irregular water supply.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.3431, 23.3949],
      address: "Morabadi, Ranchi, Jharkhand",
    },
    status: "In Progress",
    createdAt: "2025-09-13T14:00:00.000Z",
  },
  {
    title: "Garbage burning",
    description: "Locals burning garbage near Karamtoli Chowk.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.3510, 23.3720],
      address: "Karamtoli, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-13T09:00:00.000Z",
  },
  {
    title: "Defunct lamp post",
    description: "Streetlight pole damaged near Ashok Nagar.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3351, 23.3219],
      address: "Ashok Nagar, Ranchi, Jharkhand",
    },
    status: "In Progress",
    createdAt: "2025-09-12T21:00:00.000Z",
  },
  {
    title: "Broken footpath",
    description: "Pavement slabs broken near Albert Ekka Chowk.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.3255, 23.3476],
      address: "Albert Ekka Chowk, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-12T19:00:00.000Z",
  },
  {
    title: "Water contamination",
    description: "Residents of Hinoo report muddy water from taps.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.3180, 23.3305],
      address: "Hinoo, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-12T10:00:00.000Z",
  },
  {
    title: "Garbage bins overflowing",
    description: "Bins overflowing in Argora market area.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.3056, 23.3233],
      address: "Argora, Ranchi, Jharkhand",
    },
    status: "Resolved",
    createdAt: "2025-09-12T09:00:00.000Z",
  },
  {
    title: "Streetlight timing issue",
    description: "Lights at Kantatoli switch off too early in morning.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3520, 23.3500],
      address: "Kantatoli, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-11T21:00:00.000Z",
  },
  {
    title: "Uncovered drainage",
    description: "Open sewage drains near Piska More.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.2720, 23.3570],
      address: "Piska More, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-11T18:00:00.000Z",
  },
  {
    title: "No water supply",
    description: "Residents in Doranda face zero water supply today.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.3175, 23.3130],
      address: "Doranda, Ranchi, Jharkhand",
    },
    status: "In Progress",
    createdAt: "2025-09-11T10:00:00.000Z",
  },
  {
    title: "Garbage not cleared",
    description: "Waste not collected in Hindpiri locality.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.3333, 23.3533],
      address: "Hindpiri, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-10T19:00:00.000Z",
  },
  {
    title: "Streetlight broken",
    description: "Pole bent near Booty More Chowk.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3731, 23.3951],
      address: "Booty More, Ranchi, Jharkhand",
    },
    status: "Resolved",
    createdAt: "2025-09-10T15:00:00.000Z",
  },
  {
    title: "Huge potholes",
    description: "Potholes on Ratu Road stretch creating traffic jams.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.2855, 23.3602],
      address: "Ratu Road, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-10T11:00:00.000Z",
  },
  {
    title: "Water shortage",
    description: "Severe water shortage in Dhurwa colony.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.2600, 23.3015],
      address: "Dhurwa, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-10T09:30:00.000Z",
  },
  {
    title: "Illegal garbage dumping",
    description: "Garbage dumped in open near Kantatoli Chowk.",
    category: "Garbage",
    location: {
      type: "Point",
      coordinates: [85.3505, 23.3510],
      address: "Kantatoli Chowk, Ranchi, Jharkhand",
    },
    status: "In Progress",
    createdAt: "2025-09-09T20:30:00.000Z",
  },
  {
    title: "Streetlight permanently on",
    description: "Streetlight near Firayalal Chowk stays on all day.",
    category: "Streetlight",
    location: {
      type: "Point",
      coordinates: [85.3242, 23.3540],
      address: "Firayalal Chowk, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-09T17:00:00.000Z",
  },
  {
    title: "Damaged divider",
    description: "Road divider broken near Bahu Bazaar.",
    category: "Other",
    location: {
      type: "Point",
      coordinates: [85.3400, 23.3250],
      address: "Bahu Bazaar, Ranchi, Jharkhand",
    },
    status: "Pending",
    createdAt: "2025-09-09T09:00:00.000Z",
  },
  {
    title: "Dirty tap water",
    description: "Residents of Upper Bazar complain of muddy water supply.",
    category: "Water Supply",
    location: {
      type: "Point",
      coordinates: [85.3300, 23.3500],
      address: "Upper Bazar, Ranchi, Jharkhand",
    },
    status: "Resolved",
    createdAt: "2025-09-08T18:00:00.000Z",
  },
];

export default sampleComplaints;
